<?xml version="1.0"?>

<project basedir="." default="compile" name="support-tomcat" xmlns:antelope="antlib:ise.antelope.tasks">
	<import file="../build-common-java.xml" />

	<property name="deploy.dir" value="${app.server.lib.portal.dir}" />
	<property name="jar.file" value="${ant.project.name}" />
	<property name="javac.classpathref" value="web.classpath" />
	<property name="manifest.bundle.name" value="Liferay Support Tomcat" />
	<property name="manifest.bundle.symbolic.name" value="com.liferay.support.tomcat" />

	<path id="web-lib.classpath">
		<fileset
			dir="${project.dir}/lib/development"
			includes="tomcat-catalina-ha-10.1.43.jar,tomcat-catalina-10.1.43.jar,tomcat-jasper-10.1.43.jar,tomcat-api-10.1.43.jar,tomcat-coyote-10.1.43.jar,tomcat-tribes-10.1.43.jar,tomcat-util-scan-10.1.43.jar,tomcat-util-10.1.43.jar"
		/>
		<fileset
			dir="${project.dir}/lib/portal"
			includes="tomcat-juli-10.1.43.jar"
		/>
	</path>
</project>